### ISSUE TITLE
How to set options for LineBuffer when initiating twisters = new Twisters()?

### ISSUE THREAD

**Issue by djtregear** [adamjarret/twisters#1]
Hi Adam,

First things, first, brilliant piece of software!

I've been wrestling with trying to get **Ora** and then **Spinnies** to work the way I need for the past few days and had almost given up and was about to write something like this myself.

Thank you for this.  I have implemented everything I need using a custom render function. 

One last problem I have is that your **LineBuffer** implementation defaults to **handleSigint = true** and therefore registers and fires a **process.exit(128 + 2)**;

I can't seem to be able to figure out how I to set this option to false during instantiation.

Would you be able to help with this?

Many thanks in advance and once again, thanks for some quality open source code!

Cheers

David

**Comment by djtregear** [comment]
OK, just seen the examples, don't know how I missed those.  Thanks again, David.

**Comment by adamjarret** [comment]
Thanks for the kind words, David! I'm glad this package is useful to you and that you were able to find a helpful example.

Here is the link to the relevant example in case it's useful to someone reading this thread in the future: https://github.com/adamjarret/twisters/blob/master/packages/examples-js/bin/options/handleSigint.js

Cheers,

Adam
